### ISSUE TITLE
Make calendar page more responsive

### ISSUE THREAD

**Issue by lucasmarcelli** [lucasmarcelli/mood-tracker#12]

**Comment by OSP123** [comment]
Alright, I'll see if I can get some time to make it responsive.

**Comment by lucasmarcelli** [comment]
Cool beans! I'm going to take a look at your PR later today btw, I just had
a job interview pop up today randomly so I'm preparing for that!

Lucas

**Comment by OSP123** [comment]
No worries, dude. Good luck with the interview :)

**Comment by OSP123** [comment]
OK, working on this now.

**Comment by OSP123** [comment]
OK, it should be fixed. The calendar works better on mobile now (in my opinion). You might want to add a caption based on screen size that tells users to scroll right and left if they're on a mobile device.
